# Generated by Django 5.2.7 on 2025-10-15 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20, unique=True)),
                ("secid", models.CharField(blank=True, default="", max_length=20)),
                ("shortname", models.CharField(blank=True, default="", max_length=100)),
                (
                    "engine",
                    models.CharField(blank=True, default="stock", max_length=20),
                ),
                (
                    "market",
                    models.CharField(blank=True, default="shares", max_length=20),
                ),
                ("board", models.CharField(blank=True, default="TQBR", max_length=20)),
                ("lot_size", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Инструмент",
                "verbose_name_plural": "Инструменты",
            },
        ),
        migrations.CreateModel(
            name="Candle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField(db_index=True)),
                (
                    "interval",
                    models.IntegerField(
                        choices=[
                            (1, "1 мин"),
                            (10, "10 мин"),
                            (60, "1 час"),
                            (1440, "1 день"),
                        ],
                        default=1,
                    ),
                ),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candles",
                        to="mm08.instrument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свеча",
                "verbose_name_plural": "Свечи",
                "indexes": [
                    models.Index(
                        fields=["instrument", "interval", "dt"],
                        name="mm08_candle_instrum_bfa2f6_idx",
                    )
                ],
                "unique_together": {("instrument", "dt", "interval")},
            },
        ),
    ]
