# Generated by Django 5.2.7 on 2025-10-16 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mm08", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candle",
            options={
                "ordering": ["-dt"],
                "verbose_name": "Свеча",
                "verbose_name_plural": "Свечи",
            },
        ),
        migrations.AlterModelOptions(
            name="instrument",
            options={
                "ordering": ["ticker"],
                "verbose_name": "Инструмент",
                "verbose_name_plural": "Инструменты",
            },
        ),
        migrations.AddField(
            model_name="candle",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Создано",
            ),
        ),
        migrations.AddField(
            model_name="candle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
        migrations.AddField(
            model_name="instrument",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="Создано",
            ),
        ),
        migrations.AddField(
            model_name="instrument",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменено"),
        ),
    ]
