# Generated by Django 5.2.7 on 2025-10-18 17:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mm08", "0003_candle_created_by_instrument_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Создано",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "board",
                    models.CharField(db_index=True, default="TQBR", max_length=16),
                ),
                ("label", models.CharField(blank=True, default="", max_length=32)),
                ("source", models.CharField(default="moex", max_length=32)),
            ],
            options={
                "verbose_name": "Снимок теплокарты",
                "verbose_name_plural": "Снимки теплокарты",
                "ordering": ["-date", "-created_at"],
                "unique_together": {("date", "board", "label")},
            },
        ),
        migrations.CreateModel(
            name="HeatTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=20)),
                ("shortname", models.CharField(blank=True, default="", max_length=100)),
                ("engine", models.CharField(default="stock", max_length=20)),
                ("market", models.CharField(default="shares", max_length=20)),
                ("board", models.CharField(default="TQBR", max_length=20)),
                (
                    "last",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Изменение % относительно предыдущего закрытия (LASTCHANGEPRC)",
                        max_digits=8,
                    ),
                ),
                ("turnover", models.BigIntegerField(default=0)),
                ("volume", models.BigIntegerField(default=0)),
                ("lot_size", models.PositiveIntegerField(default=1)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="mm08.heatsnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Плитка теплокарты",
                "verbose_name_plural": "Плитки теплокарты",
                "ordering": ["-change_pct"],
                "indexes": [
                    models.Index(
                        fields=["snapshot", "ticker"],
                        name="mm08_heatti_snapsho_3c7fa9_idx",
                    ),
                    models.Index(
                        fields=["snapshot", "change_pct"],
                        name="mm08_heatti_snapsho_120b55_idx",
                    ),
                ],
            },
        ),
    ]
