# Generated by Django 5.2.7 on 2025-10-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mm08", "0004_heatsnapshot_heattile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heattile",
            name="change_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="Изменение % относительно предыдущего закрытия (LASTCHANGEPRC)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
