# Generated by Django 5.2.7 on 2025-10-20 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mm08", "0005_alter_heattile_change_pct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heatsnapshot",
            name="date",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
    ]
